version: "2"

services:
  app:
    image: golang:alpine
    ports:
      - "6080:80"
      - "6443:443"
    volumes:
      - .:/app
      - ./certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /app
    environment:
      - CGO_ENABLED=0
    command: go run -mod=vendor .
